version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: decorator
    versions:
    - 5.0.0
    - 5.0.5
    - 5.0.6
  - dependency-name: django
    versions:
    - 3.1.5
    - 3.1.6
    - 3.1.7
    - 3.1.8
  - dependency-name: prompt-toolkit
    versions:
    - 3.0.14
    - 3.0.15
    - 3.0.16
    - 3.0.17
  - dependency-name: pygments
    versions:
    - 2.7.4
    - 2.8.0
